name: Linux-build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: nvidia/cuda:11.8.0-devel-centos7
    steps:
    - name: Install dependencies
      run: |
        yum -y install https://packages.endpointdev.com/rhel/7/os/x86_64/endpoint-repo.x86_64.rpm
        yum -y install git curl zip unzip tar
        yum install -y centos-release-scl
        yum install -y devtoolset-8-gcc devtoolset-8-gcc-c++
        git config --global --add safe.directory "*"
        
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Get CMake 3.29.0
      run: |
          curl -L https://github.com/Kitware/CMake/releases/download/v3.29.0/cmake-3.29.0-linux-x86_64.sh -o cmake-install.sh
          chmod +x cmake-install.sh
          ./cmake-install.sh --skip-license --prefix=/usr/local

    - name: Restore from cache and setup vcpkg executable and data files.
      uses: lukka/run-vcpkg@v11.1
      with:
        vcpkgJsonGlob: 'vcpkg.json'

    - name: Build
      run: |
          scl enable devtoolset-8 bash
          cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=${sourceDir}/vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build build --config Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: xenblocksMiner-linux
        path: build/
