name: Linux-build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: nvidia/cuda:11.8.0-devel-centos7
    steps:
    - name: Install dependencies
      run: |
        yum -y remove git
        yum -y remove git-*
        yum -y install https://packages.endpointdev.com/rhel/7/os/x86_64/endpoint-repo.x86_64.rpm
        yum -y install git unzip
        git --version
        
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Checkout submodules
      run: |
        git submodule update --init --recursive
        
    - uses: lukka/get-cmake@v3.24.3

    - name: Restore from cache and setup vcpkg executable and data files.
      uses: lukka/run-vcpkg@v11.1
      with:
        vcpkgJsonGlob: 'vcpkg.json'

    - name: Run CMake+vcpkg+Ninja+CTest to build packages and generate/build/test the code.
      uses: lukka/run-cmake@v10.6
      with:
        configurePresetAdditionalArgs: "['-S . -B build -DCMAKE_TOOLCHAIN_FILE=${sourceDir}/vcpkg/scripts/buildsystems/vcpkg.cmake']"
        buildPresetAdditionalArgs: "['--build build --config Release']"

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: xenblocksMiner-linux
        path: build/bin
