name: Linux-build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: nvidia/cuda:11.8.0-devel-centos7
    steps:
    - name: Install dependencies
      run: |
        yum install -y centos-release-scl
        yum install -y rh-git218
        echo "source scl_source enable rh-git218" >> $BASH_ENV
        git --version
        
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: lukka/get-cmake@latest

    - name: Restore from cache and setup vcpkg executable and data files.
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: 'vcpkg.json'

    - name: Run CMake+vcpkg+Ninja+CTest to build packages and generate/build/test the code.
      uses: lukka/run-cmake@v10
      with:
        configurePresetAdditionalArgs: "['-S . -B build -DCMAKE_TOOLCHAIN_FILE=${sourceDir}/vcpkg/scripts/buildsystems/vcpkg.cmake']"
        buildPresetAdditionalArgs: "['--build build --config Release']"

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: xenblocksMiner-linux
        path: build/bin
